# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eric Daly Blog
email: ericdalyblog@dalydays.com
description: > # this means to ignore newlines until "baseurl:"
  Find out what Eric Daly is learning about, and how to do things that should be easy but turn out to be more difficult than expected!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericdalyblog.dalydays.com" # the base hostname & protocol for your site
#twitter_username: linucksrox
github_username:  linucksrox

# Build settings
markdown: kramdown
